// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/Card.vue')['default']
    Category: typeof import('./src/fragments/Category.vue')['default']
    Comments: typeof import('./src/fragments/essay/Comments.vue')['default']
    Common: typeof import('./src/fragments/Common.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Essay: typeof import('./src/fragments/essay/Essay.vue')['default']
    EssayBottomData: typeof import('./src/components/EssayBottomData.vue')['default']
    GitHub: typeof import('./src/components/GitHub.vue')['default']
    Home: typeof import('./src/fragments/Home.vue')['default']
    LeftSide: typeof import('./src/fragments/LeftSide.vue')['default']
    MyTags: typeof import('./src/fragments/MyTags.vue')['default']
    Navigator: typeof import('./src/fragments/Navigator.vue')['default']
    RightSide: typeof import('./src/fragments/RightSide.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tag: typeof import('./src/components/Tag.vue')['default']
    TagPage: typeof import('./src/fragments/TagPage.vue')['default']
  }
}
