// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/Card.vue')['default']
    Category: typeof import('./src/views/modules/home/Category.vue')['default']
    Comments: typeof import('./src/views/fragments/Comments.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Essay: typeof import('./src/views/modules/Essay.vue')['default']
    EssayBottom: typeof import('./src/views/fragments/EssayBottom.vue')['default']
    EssayItem: typeof import('./src/views/adapters/EssayItem.vue')['default']
    GitHub: typeof import('./src/views/fragments/GitHub.vue')['default']
    Home: typeof import('./src/views/modules/home/Home.vue')['default']
    LeftSidebar: typeof import('./src/views/fragments/LeftSidebar.vue')['default']
    MyTags: typeof import('./src/views/modules/home/MyTags.vue')['default']
    Navigator: typeof import('./src/views/fragments/Navigator.vue')['default']
    PaginationPage: typeof import('./src/components/PaginationPage.vue')['default']
    RightSidebar: typeof import('./src/views/fragments/RightSidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideItem: typeof import('./src/views/adapters/SideItem.vue')['default']
    SkillGraph: typeof import('./src/components/SkillGraph/SkillGraph.vue')['default']
    Tag: typeof import('./src/components/Tag.vue')['default']
    TagPage: typeof import('./src/views/modules/home/TagPage.vue')['default']
  }
}
